Code voor gui testen met pipeline en uitbereiding main pipeline
leonvsc/software-kwaliteit-testen pull request #7
Opened 2024-01-12 19:44 UTC by NielsWarnaar

Dit pr bevat code voor de gui tests. Deze testen zijn gemaakt met playwright. 
De pipeline draait de testen op Chromium, Firefox en Webkit. Naast het draaien van de tests op de playwright browsers, is er ook een test gemaakt met saucelabs. 
Door de gratis versie kan hier enkel een browser getest worden. Nu wordt enkel Firefox in saucelabs getest, al kan dit eenvoudig aangepast worden indien gewenst. 

De pipeline van de testen is gekoppeld aan de main pipeline.

2024-01-12 22:40 UTC, Boogieguy4 requested changes
Alles ziet er goed uit, van mij heb je een go op een paar kleine puntjes na.

2024-01-12 22:40 UTC, Boogieguy4 commented on .github/workflows/pipeline-qa.yml
Bij line 9 staat een wildcard waardoor de workflow runned als op elke branch iets gepushed wordt. Willen we dit?

2024-01-12 22:40 UTC, Boogieguy4 commented on .github/workflows/playwright.yml
Ziet er goed uit, ik zou alleen wel allemaal even naar de versie v4 zetten. Dit is de laaste major stable versie voor alle actions die je gebruikt.

2024-01-12 22:40 UTC, Boogieguy4 commented on .gitignore
Deze file zou ik gewoon weg laten op de remote. Als je dat goed vind haal ik hem voor je weg.

2024-01-13 14:27 UTC, NielsWarnaar commented on .github/workflows/pipeline-qa.yml
Ik had het gedaan om te kijken of de pipeline goed werkt, alleen kan ik hem weghalen.

2024-01-13 14:27 UTC, NielsWarnaar commented on .github/workflows/playwright.yml
Thanks voor de tip, ik ga zo kijken of alles dan nog werkt

2024-01-13 14:28 UTC, NielsWarnaar commented on .gitignore
Waarom? Als ik hem weghaal, dan push ik bestanden mee die niet nodig zijn (de node-modules bijv.)

2024-01-13 16:18 UTC, Boogieguy4 commented on .gitignore
Ja laat dan maar staan geef opzich niet. Bij mij negeert die de bestanden alsnog, zonder dat ik de gitignore commit vandaar.

2024-01-13 20:39 UTC, Boogieguy4 approved these changes
Alles is toppie.

2024-01-13 20:45 UTC, merged